permit_join:
  description: Allow pairing new device.

identify_device:
  description: >
    Automatically identify a device's destination endpoint.
    Be aware that devices running on battery need to be woken up to answer,
    typically by pushing the pairing button.
    You should provide the entity_id OR the addr.
  fields:
    entity_id:
      description: The device entity_id to identify
      example: 'zigate.0123456789abcdef'
    addr:
      description: ZiGate address of the device.
      example: '0123'

refresh_device:
  description: >
    Refresh a device by sending many requests to it.
    Be aware that devices running on battery need to be woken up to answer,
    typically by pushing the pairing button.
    You should provide the entity_id OR the addr.
    If no parameter is provided, every devices will be refreshed.
  fields:
    entity_id:
      description: The device entity_id to refresh
      example: 'zigate.0123456789abcdef'
    addr:
      description: ZiGate address of the device.
      example: '0123'

remove_device:
  description: >
    Remove device
  fields:
    entity_id:
      description: The device entity_id to refresh
      example: 'zigate.0123456789abcdef'
    addr:
      description: ZiGate address of the device.
      example: '0123'

raw_command:
  description: Send a raw command to zigate.
  fields:
    cmd:
      description: Command code
      example: '0x0092'
    data:
      description: Payload in hex format.
      example: '020123010101'
